
steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '-t'
    - 'us-west1-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY_REPO}/pyspak_sample_pipeline:${SHORT_SHA}'
    - '-t'
    - 'us-west1-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY_REPO}/pyspak_sample_pipeline:latest'
    - '.'

- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'push'
  - 'us-west1-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY_REPO}/pyspak_sample_pipeline'
  - '--all-tags'
